export const default_course_poster =
  'https://skpquxxzpjcxtzckwszq.supabase.co/storage/v1/object/sign/nx-escola/default_course_poster.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJueC1lc2NvbGEvZGVmYXVsdF9jb3Vyc2VfcG9zdGVyLnBuZyIsImlhdCI6MTYyNTg0Mzk1NSwiZXhwIjoxOTQxMjAzOTU1fQ.hycklX7A56TARTbEtw-RjxanExQzYEPm41sFj8JrnxM';
