import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { supabase } from '../utils/supabase';

export default function Home({ courses }) {
  const mapCourses = () => {
    return courses
      .map((course, index) => (
        <div key={index}>
          <p>{course.id}</p>
        </div>
      ))
      .reverse();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1>OI</h1>
        {courses.length === 0 ? <p>Courses not found.</p> : mapCourses()}
      </main>

      <footer className={styles.footer}>footer</footer>
    </div>
  );
}

export async function getStaticProps() {
  let { data: courses, error } = await supabase.from('courses').select('*');

  if (error) throw error;

  return {
    props: { courses },
  };
}
